# Generated by Django 4.2.7 on 2024-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LaptopName', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
