# Generated by Django 4.2.7 on 2024-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='ProductName',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
