# Generated by Django 4.2.7 on 2024-06-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
    ]
