# Generated by Django 4.2.7 on 2024-06-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0015_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='static/Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='static/Products'),
        ),
    ]
