# Generated by Django 4.2.7 on 2024-07-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0017_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
